/*
 * Summarizing2.java
 *
 * Created on November 13, 2008, 8:29 PM
 */

package UserInterfaceDesign;

import Abstract.absDOCParser;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pdf.DOCRead;
import pdf.DOCWriter;
import pdf.Parser;
import pdf.ReaderPDF;
import pdf.TotalDocumentFrequencyParser;
import pdf.uni;

/**
 *
 * @author  mar
 */
public class Summarizing2 extends javax.swing.JFrame {
    private Summarizer s=new Summarizer();

    private String output;

    private String filename;

    private String summaryfile;
    /** Creates new form Summarizing2 */
    public Summarizing2()  {
        initComponents();
         this.jComboBox1.insertItemAt("Abstract word frequency",0);
        this.jComboBox1.insertItemAt("Total Document Word Frequency",1);
        this.jComboBox1.setSelectedIndex(0);
         this.jComboBox2.insertItemAt("word",0);
        this.jComboBox2.insertItemAt("pdf",1);
        this.jComboBox2.setSelectedIndex(0);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mar\\Final\\pic\\pic1-1.jpg"));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mar\\Final\\pic\\pic3-1.jpg"));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("\u0627\u0646\u062a\u062e\u0627\u0628 \u0631\u0648\u0634 \u062e\u0644\u0627\u0635\u0647 \u0633\u0627\u0632\u06cc  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("\u0627\u0646\u062a\u062e\u0627\u0628 \u0641\u0631\u0645\u062a \u0641\u0627\u06cc\u0644 \u062e\u0631\u0648\u062c\u06cc ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, -1));

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 130, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("\u0635\u0641\u062d\u0647 \u0642\u0628\u0644");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("\u062e\u0627\u0646\u0647");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 80, -1));

        jLabel6.setText("\u0641\u0627\u06cc\u0644 \u0645\u0648\u0631\u062f \u0646\u0638\u0631 \u062f\u0631 \u067e\u0648\u0634\u0647 \u0646\u0635\u0628 \u062f\u0631 \u0633\u06cc \u062f\u06cc \u0628\u0631\u0646\u0627\u0645\u0647 \u0645\u0648\u062c\u0648\u062f \u0645\u06cc \u0628\u0627\u0634\u062f");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("\u0627\u0646\u062a\u062e\u0627\u0628 \u0641\u0627\u06cc\u0644 \u062d\u0627\u0648\u06cc \u0644\u063a\u0627\u062a \u0645\u0639\u0645\u0648\u0644");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("\u0646\u0645\u0627\u06cc\u0634 \u0641\u0627\u06cc\u0644 \u062e\u0644\u0627\u0635\u0647 \u0634\u062f\u0647");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        Summarizer s=new Summarizer();
        DOCRead doc=new DOCRead();
        summaryfile="summary.doc";
        try{
            if(jComboBox1.getSelectedIndex()==1) {
                TotalDocumentFrequencyParser tdp=new TotalDocumentFrequencyParser();
                output=tdp.parsing_Words(filename,doc.text);
            } else if(jComboBox1.getSelectedIndex()==0) {
                absDOCParser abs=new absDOCParser();
                output=abs.parsing_Words(filename,doc.text);
                
            }
            DOCWriter dc=new DOCWriter();
            dc.writer(summaryfile,output);
            
            // Parser p=new Parser();
            // p.writer(output);
            Desktop.getDesktop().open(new File(summaryfile));
            
            
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
/*          try {
            Desktop.getDesktop().open( new File(s.filename) );
        } catch ( Exception /* IOException, URISyntaxException  e ) {
           /* e.printStackTrace();
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
        JFileChooser jf = new JFileChooser("e:\\");
        int r = jf.showOpenDialog(null);
        
        
        
        if(r == JFileChooser.OPEN_DIALOG) {
            
            filename = jf.getSelectedFile().getAbsolutePath();
            if(filename.endsWith("pdf")==true||filename.endsWith("doc")==true) {
                try{
                    this.jLabel4.setText(filename);
                    this.jLabel4.setVisible(true);
                    
                } catch(Exception e) {
                    System.out.println(e.getMessage());
                }
            }
            
            //EndRead
        }else {
            JOptionPane.showMessageDialog(null,"Select pdf or doc File");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:

        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                new Summarizing2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
